version: '2'

services:
  nats:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STREAM_NAMES=payments,suppliers,verifications
      - NATS_SERVER=0.0.0.0:4222
    expose:
      - '4222'
    ports:
      - '4222:4222'
      - '8222:8222'
    hostname: nats
    volumes:
      - './nats-server.conf:/nats-server.conf'
      - './data:/data/jetstream'
      - './entrypoint.sh:/entrypoint.sh'
    command: ['ash', '/entrypoint.sh']
