allowBuilds:
  '@apollo/protobufjs': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@swc/core': true
  bcrypt: true
  core-js-pure: true
  esbuild: true
  less: true
  msw: true
  nx: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.0'
  - '@typescript-eslint/eslint-plugin@8.59.4'
  - '@typescript-eslint/parser@8.59.4'
  - '@typescript-eslint/project-service@8.59.4'
  - '@typescript-eslint/scope-manager@8.59.4'
  - '@typescript-eslint/tsconfig-utils@8.59.4'
  - '@typescript-eslint/type-utils@8.59.4'
  - '@typescript-eslint/types@8.59.4'
  - '@typescript-eslint/typescript-estree@8.59.4'
  - '@typescript-eslint/utils@8.59.4'
  - '@typescript-eslint/visitor-keys@8.59.4'
  - date-fns@4.2.1
  - ts-jest@29.4.10
