import '@recharge/tailwind/global-css';

import type { ReactNode } from 'react';

import { GraphqlPageProvider } from './graphql-page-provider';

export const metadata = {
  title: 'Welcome to recharge-fe',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang='en'>
    <body>
      <GraphqlPageProvider>{children}</GraphqlPageProvider>
    </body>
  </html>
);

export default RootLayout;
