#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --name-only HEAD@{1} HEAD | grep --silent '^pnpm-lock\.yaml'; then
  echo "📦 pnpm-lock.yaml was changed."
  echo "Running pnpm install to update your dependencies..."
  pnpm install
fi
